### ISSUE TITLE
有个问题，如果把chosen的select放在一个隐藏的div中，结果切换显示这个DIV后，chosen效果width变成了0？如何解决？

### ISSUE THREAD

**Issue by m55z** [amazeui/chosen#2]
有个问题，如果把chosen的select放在一个隐藏的div中，结果切换显示这个DIV后，chosen效果width变成了0？如何解决？

**Comment by m55z** [comment]
有重新渲染的方法吗？

**Comment by minwe** [comment]
你可以试试先销毁再重新初始化：

```js
$('#xxx').chosen('destroy').chosen({
  // ...
});
```

**Comment by m55z** [comment]
亲，用了你的建议试了下，不行，我把demo发上来，你能帮我看下吗？

`<!Doctype html>`
`<html class="no-js">`
`<head>`
`<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`
`<title>测试</title>`
`<link rel="stylesheet" href="http://amazeui.github.io/chosen/amazeui.chosen.css" />`
`<script src="http://cdn.bootcss.com/jquery/1.8.3/jquery.min.js"></script>`
`<script src="http://amazeui.github.io/chosen/amazeui.chosen.js"></script>`
`</head>`
`<body>`
`<div class="tab_mod">`
`	<ul>`
`        <li><a onClick="$('#form1').show();$('#form2').hide();">表单一</a></li>`
`        <li><a onClick="$('#form1').hide();$('#form2').show();">表单二</a></li>`
`    </ul>`
`</div>`
`<div class="formfields" id="form1">`
`	表单一正常
`</div>
`<div class="formfields" id="form2" style="display:none;">`
`	<select id="test">`
`    	<option>选项A</option>`
`        <option>选项B</option>`
`    </select>`
`</div>`
`<script>`
`$(function(){`
`	$("select#test").chosen('destroy').chosen({`
`	`	
`	});`
`})`
`</script>`
`</body>`
`</html>`

**Comment by minwe** [comment]
```html
<!Doctype html>
<html class="no-js">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>测试</title>
  <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.6.2/css/amazeui.min.css" />
  <link rel="stylesheet"
        href="http://amazeui.github.io/chosen/amazeui.chosen.css" />
  <script src="http://cdn.bootcss.com/jquery/1.8.3/jquery.min.js"></script>
  <script src="http://amazeui.github.io/chosen/amazeui.chosen.js"></script>
</head>
<body>
<div class="tab_mod">
  <ul>
    <li><a rel="form1">表单一</a></li>
    <li><a rel="form2">表单二</a></li>
  </ul>
</div>
<div class="formfields" id="form1">
  表单一正常
</div>
<div class="formfields" id="form2" style="display:none;">
  <select id="test">
    <option>选项 A xxxxxx</option>
    <option>选项 B xxxxxx</option>
  </select>
</div>
<script>
  $(function() {
    var $forms = $('.formfields');
    $('.tab_mod a').on('click', function() {
      var rel = this.getAttribute('rel');
      var $form = $('#' + rel).show();
      $forms.not($form).hide();
      $form.find('select').chosen('destroy').chosen();
    });
  })
</script>
</body>
</html>
```

显示以后再执行 chosen 相关操作。

**Comment by m55z** [comment]
感谢大神！~

**Comment by minwe** [comment]
建议多熟悉基础知识，了解背后的运行逻辑才能更好的运用。
